### ISSUE TITLE
intent not detected

### ISSUE THREAD

**Issue by shilbert01** [maxbachmann-snips/MM2-HideShowMove#1]
https://github.com/maxbachmann-snips/MM2-HideShowMove/blob/master/action-maxbachmann-MM2-HideShowMove.py

intentname = data['intent']['intentName'].rsplit(':')[0]

results in "maxbachmann"

I supposed it needs to be rsplit(':')[1]              ??

**Comment by maxbachmann** [comment]
This is fixed with commit fdb24c2
